### ISSUE TITLE
Dependency installation error on Ubuntu

### ISSUE THREAD

**Issue by debadeepta** [naszilla/naszilla#22]
Dear Naszilla team,

I am getting this error when I try to install. It seems that pip can no longer find tensorflow 1.14.0 in the standard pathways. This is an Ubuntu 18.04 64 bit system witha P100 gpu.

(base) dedey@ubuntubox:~/naszilla$ cat requirements.txt | xargs -n 1 -L 1 pip install
ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14.0
ERROR: No matching distribution found for tensorflow-gpu==1.14.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0
ERROR: No matching distribution found for tensorflow==1.14.0

**Comment by crwhite14** [comment]
Hi Dey, thanks for your interest.

I believe this repository works for `tensorflow-gpu==1.15.4` as well (and likely all versions between 1.14.0 and 1.15.4).
Unfortunately it does not work with tensorflow 2 because the requirement `nasbench` does not work with tensorflow 2.

I hope that is helpful. One more thing - all code in the `naszilla/naszilla` repository runs just fine on a CPU, thanks to the NAS-Bench-101/201/301 datasets!
